#include <stdio.h>
#include <stdlib.h>
#include <omp.h>
#include <math.h>
#include <string.h>
#include <mpi.h>
#include "gen_points.h"
#include "point_operations.h"
#include "ball_tree.h"
#include "macros.h"

int n_dims; // number of dimensions of each point

double **pts; // list of points of the current iteration of the algorithm
double **ortho_array; // list of ortogonal projections of the points in pts
double **ortho_array_srt; //list of ortogonal projections of the point in pts to be sorted.
double **pts_aux; // list of points of the next iteration of the algorithm

long n_points_local; //number of points in the dataset present at this process
long n_points_global; //number of points in the dataset present at all processes

double  *basub; // point containing b-a for the orthogonal projections
double *ortho_tmp; // temporary pointer used for calculation the orthogonal projection

node_ptr node_list; // list of nodes of the ball tree
double** node_centers; // list of centers of the ball tree nodes

long n_nodes; // number of nodes of the ball tree
long node_id; // id of the current node of the algorithm
long node_counter; // number of nodes generated by the program

int rank; //rank of the current process
int n_procs; //total number of processes

long *processes_n_points; //array of the number of points owned by each process currently

/*
Returns the point in pts furthest away from point p
*/
double* get_furthest_away_point(double* p) {
    double max_distance = 0.0;
    double* furthest_point = p;
    for(long i = 0; i < n_points_local; i++){
        double curr_distance = distance(p, pts[i]);
        if(curr_distance > max_distance){
            max_distance = curr_distance;
            furthest_point = pts[i];
        }
    }
    return furthest_point;
}

/*
Returns the radius of the ball tree node defined by point center
*/
double get_radius(double* center) {
    double* a = get_furthest_away_point(center);
    return sqrt(distance(a, center));
}

/*
Used for quicksort
Compares the x coordenate of the two points
*/
int compare_node(const void* pt1, const void* pt2) {
    double* dpt1 = *((double**) pt1);
    double* dpt2 = *((double**) pt2);

    if(dpt1[0] > dpt2[0]) {
        return 1;
    }
    else if(dpt1[0] < dpt2[0]) {
        return -1;
    }
    else {
        return 0;
    }
}

/*
Returns the median projection of the dataset
by sorting the projections based on their x coordinate
*/
double* get_center() {
    memcpy(ortho_array_srt, ortho_array, sizeof(double*) * n_points_local);
    qsort(ortho_array_srt, n_points_local, sizeof(double*), compare_node);

    if(n_points_local % 2) { // is odd
        long middle = (n_points_local - 1) / 2;
        copy_point(ortho_array_srt[middle], node_centers[node_id]);
    }
    else { // is even
        long first_middle = (n_points_local / 2) - 1;
        long second_middle = (n_points_local / 2);

        middle_point(ortho_array_srt[first_middle], ortho_array_srt[second_middle], node_centers[node_id]);
    }
    return node_centers[node_id];
}

/*
Computes the orthogonal projections of points in pts onto line defined by b-a
*/
void calc_orthogonal_projections(double* a, double* b) {
    sub_points(b, a, basub);
    for(long i = 0; i < n_points_local; i++){
        orthogonal_projection(basub, a, pts[i], ortho_array[i], ortho_tmp);
    }
}

/*
Places each point in pts in partition left or right by comparing the x coordinate
of its orthogonal projection with the x coordinate of the center point
*/
void fill_partitions(double** left, double** right, double* center) {
    long l = 0;
    long r = 0;
    for(long i = 0; i < n_points_local; i++) {
        if(ortho_array[i][0] < center[0]) {
            left[l] = pts[i];
            l++;
        }
        else {
            right[r] = pts[i];
            r++;
        }
    }
}

void build_tree() {
    if(n_points_local == 1) {
        make_node(node_id, pts[0], 0, &node_list[node_id]);
        return;
    }

    double* a = get_furthest_away_point(pts[0]);
    double* b = get_furthest_away_point(a);

    calc_orthogonal_projections(a, b);

    double* center = get_center();
    double radius = get_radius(center);

    node_ptr node = make_node(node_id, center, radius, &node_list[node_id]);

    double **left = pts_aux;
    double **pts_aux_left = pts;
    double **ortho_array_left = ortho_array;
    double **ortho_array_srt_left = ortho_array_srt;
    long n_points_local_left = LEFT_PARTITION_SIZE(n_points_local);

    double **right = pts_aux + n_points_local_left;
    double **pts_aux_right = pts + n_points_local_left;
    double **ortho_array_right = ortho_array + n_points_local_left;
    double **ortho_array_srt_right = ortho_array_srt + n_points_local_left;
    long n_points_local_right = RIGHT_PARTITION_SIZE(n_points_local);

    long node_id_left = ++node_counter;
    long node_id_right = ++node_counter;

    fill_partitions(left, right, center);

    pts = left;
    pts_aux = pts_aux_left;
    ortho_array = ortho_array_left;
    ortho_array_srt = ortho_array_srt_left;
    n_points_local = n_points_local_left;
    node_id = node_id_left;
    build_tree();

    pts = right;
    pts_aux = pts_aux_right;
    ortho_array = ortho_array_right;
    ortho_array_srt = ortho_array_srt_right;
    n_points_local = n_points_local_right;
    node_id = node_id_right;
    build_tree();

    node->left_id = node_id_left;
    node->right_id = node_id_right;
}

/*
Get the points currently held by other processes
*/
void get_other_processes_n_points() {
    long my_points = n_points_local;
    MPI_Allgather(
        &my_points, //the address of the data the current process is sending
        1, //number of data elements sent
        MPI_LONG, //type of data element sent
        processes_n_points, //the address where the current process stores the data received
        1, //number of dta elements sent by each process
        MPI_LONG, //type of data element received
        MPI_COMM_WORLD //sending and receiving to all processes
    );

    for(int i = 0; i < n_procs; i ++) {
        printf("%d processes_n_points[%d]=%ld\n", rank, i, processes_n_points[i]);
    }
}

void get_first_point() {

}

void build_tree_mpi() {

    /**/
    get_other_processes_n_points();

    get_first_point();

    //get_furthest_away_point of first point is a

    //get_furthest_away_point of a is b

    //calc_orthogonal_projections

    //sort projections

    //calc left and right points


}

void alloc_memory() {
    long n_points_ceil = (long) (ceil((double) (n_points_global) / (double) (n_procs)));

    n_points_local = BLOCK_SIZE(rank, n_procs, n_points_global);
    n_nodes = (n_points_global * 2) - 1;

    pts_aux = (double**) malloc(sizeof(double*) * n_points_ceil);

    ortho_array = create_array_pts(n_dims, n_points_ceil);
    ortho_array_srt = (double**) malloc(sizeof(double*) * n_points_ceil);

    basub = (double*) malloc(sizeof(double) * n_dims);
    ortho_tmp = (double*) malloc(sizeof(double) * n_dims);

    node_list = (node_ptr) malloc(sizeof(node_t) * n_nodes);
    node_centers = create_array_pts(n_dims, n_nodes);
    processes_n_points = (long*) malloc(sizeof(long) * n_procs);
}

int main(int argc, char** argv) {
    double exec_time;
    exec_time = -omp_get_wtime();

    MPI_Init (&argc, &argv);
    MPI_Comm_rank (MPI_COMM_WORLD, &rank);
    MPI_Comm_size (MPI_COMM_WORLD, &n_procs);

    pts = get_points(argc, argv, &n_dims, &n_points_global);
    alloc_memory();

    build_tree_mpi();
    /*
    build_tree();
    */

    exec_time += omp_get_wtime();
    /*
    if (!rank) {
        fprintf(stderr, "%.1lf\n", exec_time);
        printf("%d %ld\n", n_dims, n_nodes);
    }
    dump_tree();
    */
    MPI_Finalize();
}