#include <stdio.h>
#include <stdlib.h>
#include <omp.h>
#include <math.h>
#include <string.h>
#include "gen_points.h"
#include "point_operations.h"
#include "ball_tree.h"

int n_dims; // number of dimensions of each point

double **pts; // list of points of the current iteration of the algorithm
double **ortho_array; // list of ortogonal projections of the points in pts
double **ortho_array_srt; //list of ortogonal projections of the point in pts to be sorted.
double **pts_aux; // list of points of the next iteration of the algorithm

long n_points; //number of points in the dataset

node_ptr node_list; // list of nodes of the ball tree
double** node_centers; // list of centers of the ball tree nodes

long n_nodes; // number of nodes of the ball tree
long node_id; // id of the current node of the algorithm
long node_counter; // number of nodes generated by the program

#pragma omp threadprivate(pts,pts_aux,ortho_array, ortho_array_srt, n_points, node_id)

omp_lock_t nodelock;

double** thread_ortho_tmps; //ortho_tmp point for each thread to use when computing orthogonal projections
double** basub; // point containing b-a for the orthogonal projections

int maxdepth;

#define LEFT_PARTITION_SIZE(N) ((N) % 2 ? ((N) - 1) / 2 : (N) / 2)
#define RIGHT_PARTITION_SIZE(N) ((N) % 2 ? ((N) + 1) / 2 : (N) / 2)

/*
Returns the point in pts furthest away from point p
*/
double* get_furthest_away_point(double* p) {
    double max_distance = 0.0;
    double* furthest_point = p;
    for(long i = 0; i < n_points; i++){
        double curr_distance = distance(p, pts[i]);
        if(curr_distance > max_distance){
            max_distance = curr_distance;
            furthest_point = pts[i];
        }
    }
    return furthest_point;
}

/*
Returns the radius of the ball tree node defined by point center
*/
double get_radius(double* center) {
    double* a = get_furthest_away_point(center);
    return sqrt(distance(a, center));
}

/*
Used for quicksort
Compares the x coordenate of the two points
*/
int compare_node(const void* pt1, const void* pt2) {
    double* dpt1 = *((double**) pt1);
    double* dpt2 = *((double**) pt2);

    if(dpt1[0] > dpt2[0]) {
        return 1;
    }
    else if(dpt1[0] < dpt2[0]) {
        return -1;
    }
    else {
        return 0;
    }
}

/*
Returns the median projection of the dataset
by sorting the projections based on their x coordinate
*/
double* get_center() {
    memcpy(ortho_array_srt, ortho_array, sizeof(double*) * n_points);
    qsort(ortho_array_srt, n_points, sizeof(double*), compare_node);

    if(n_points % 2) { // is odd
        long middle = (n_points - 1) / 2;
        copy_point(ortho_array_srt[middle], node_centers[node_id]);
    }
    else { // is even
        long first_middle = (n_points / 2) - 1;
        long second_middle = (n_points / 2);

        middle_point(ortho_array_srt[first_middle], ortho_array_srt[second_middle], node_centers[node_id]);
    }
    return node_centers[node_id];
}

/*
Computes the orthogonal projections of points in pts onto line defined by b-a
*/
void calc_orthogonal_projections(double* a, double* b) {
    double* basub_tmp;
    basub_tmp = basub[omp_get_thread_num()];
    sub_points(b, a, basub_tmp);
    double* ortho_tmp;
    ortho_tmp = thread_ortho_tmps[omp_get_thread_num()];
    for(long i = 0; i < n_points; i++){
        orthogonal_projection(basub_tmp, a, pts[i], ortho_array[i], ortho_tmp);
    }
}

/*
Places each point in pts in partition left or right by comparing the x coordinate
of its orthogonal projection with the x coordinate of the center point
*/
void fill_partitions(double** left, double** right, double* center) {
    long l = 0;
    long r = 0;
    for(long i = 0; i < n_points; i++) {
        if(ortho_array[i][0] < center[0]) {
            left[l] = pts[i];
            l++;
        }
        else {
            right[r] = pts[i];
            r++;
        }
    }
}

void build_tree(int depth) {
    if(n_points == 1) {
        make_node(node_id, pts[0], 0, &node_list[node_id]);
        return;
    }

    double* a = get_furthest_away_point(pts[0]);
    double* b = get_furthest_away_point(a);

    calc_orthogonal_projections(a, b);

    double* center = get_center();
    double radius = get_radius(center);

    node_ptr node = make_node(node_id, center, radius, &node_list[node_id]);
    
    double **left = pts_aux;
    double **pts_aux_left = pts;
    double **ortho_array_left = ortho_array;
    double **ortho_array_srt_left = ortho_array_srt;
    long n_points_left = LEFT_PARTITION_SIZE(n_points);

    double **right = pts_aux + n_points_left;
    double **pts_aux_right = pts + n_points_left;
    double **ortho_array_right = ortho_array + n_points_left;
    double **ortho_array_srt_right = ortho_array_srt + n_points_left;
    long n_points_right = RIGHT_PARTITION_SIZE(n_points);

    omp_set_lock(&nodelock);

    long node_id_left = ++node_counter;
    long node_id_right = ++node_counter;

    omp_unset_lock(&nodelock);

    fill_partitions(left, right, center);

    if(depth <= maxdepth){
        #pragma omp parallel
        #pragma omp single
        {
            #pragma omp task
            {
                pts = left;
                pts_aux = pts_aux_left;
                ortho_array = ortho_array_left;
                ortho_array_srt = ortho_array_srt_left;
                n_points = n_points_left;
                node_id = node_id_left;
                build_tree(depth+1);
            }

            pts = right;
            pts_aux = pts_aux_right;
            ortho_array = ortho_array_right;
            ortho_array_srt = ortho_array_srt_right;
            n_points = n_points_right;
            node_id = node_id_right;
            build_tree(depth+1);


            #pragma omp taskwait
            
        }
    }
    else{
        pts = left;
        pts_aux = pts_aux_left;
        ortho_array = ortho_array_left;
        ortho_array_srt = ortho_array_srt_left;
        n_points = n_points_left;
        node_id = node_id_left;
        build_tree(depth+1);

        pts = right;
        pts_aux = pts_aux_right;
        ortho_array = ortho_array_right;
        ortho_array_srt = ortho_array_srt_right;
        n_points = n_points_right;
        node_id = node_id_right;
        build_tree(depth+1);
    }


   

    node->left_id = node_id_left;
    node->right_id = node_id_right;
}

void alloc_memory() {
    int nthreads = omp_get_max_threads();
    thread_ortho_tmps = (double**) malloc(sizeof(double*) * nthreads);
    for(int i = 0; i < nthreads; i++){
        thread_ortho_tmps[i] = (double*) malloc(sizeof(double) * n_dims);
    }
    basub = (double**)malloc(sizeof(double*) * nthreads);
    for(int i = 0; i < nthreads; i++){
        basub[i] = (double*) malloc(sizeof(double) * n_dims);
    }
    n_nodes = (n_points * 2) - 1;
    ortho_array = create_array_pts(n_dims, n_points);
    ortho_array_srt = (double**) malloc(sizeof(double*) * n_points);
    pts_aux = (double**) malloc(sizeof(double*) * n_points);
    node_list = (node_ptr) malloc(sizeof(node_t) * n_nodes);
    node_centers = create_array_pts(n_dims, n_nodes);
}

int main(int argc, char** argv) {
    int depth = 1;
    maxdepth = (int) log2(omp_get_max_threads());
    double exec_time;
    exec_time = -omp_get_wtime();
    pts = get_points(argc, argv, &n_dims, &n_points);
    alloc_memory();
    omp_init_lock(&nodelock);
    build_tree(depth);
    exec_time += omp_get_wtime();
    fprintf(stderr, "%.2lf\n", exec_time);
    printf("%d %ld\n", n_dims, n_nodes);
    dump_tree();
}